spring.application.name=SpringBoot_DataJPA



spring.datasource.url=jdbc:mysql://localhost:3306/Spring_jpa
spring.datasource.username=root
spring.datasource.password=Ashu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true